# Generated by Django 4.1.7 on 2023-03-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestConsulta', '0002_alter_paciente_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='rg',
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
